### ISSUE TITLE
rendering quality ?

### ISSUE THREAD

**Issue by DaveInDev** [Tyyppi77/imgui_sdl#15]
Hi Tyyppi77,
first thanks for this imgui_sdl tool. As I am quite new to ImGUI, I would like to understand one thing. And please do not take it as a critic, it's just curiosity from a newbie who wants to understand. 

I wonder why your implementation of ImGUI does not look "as good" as the DX-SDL example from the official release ? (see image at the end for comparison). I tried without any success to edit the original DX-SDL example in order to add a SDL_Renderer and to draw some rects and textures on it, while still displaying ImGUI at the same time, but without any success. It seems that SDL and ImGUI don't want to share the same window... So it seems that you give the only solution to mix SDL-rendering capabilities and ImGUI....

I wrote a little game with SDL2 / DX and I'd love to add ImGUI over it, but (no offense) I would like the original ImGui graphic quality. Do you have any suggestion for this ? I wonder if there is a way to get a DirectX handle from ImGUI and to pass it to SDL, or vice-versa, so taht both of them work on teh same device with their original quality ?

Nota : I read that you said "As you can see the results are not perfect, but this display is definitely good enough to be used as a debug UI which is the main use case for Dear ImGui anyways."  That's why I feel not too bad to ask you this question ;-)

![image](https://user-images.githubusercontent.com/20345939/79640769-aebcb600-8193-11ea-87d4-f6b8843fe93d.png)

**Comment by Tyyppi77** [comment]
I'm not sure what in particular you refer as the difference in those two pictures, but there are two main points related to the output quality of ImGuiSDL:
1) For performance reasons, rectangles are much faster to render with SDL_Renderer, and that's why the default style ImGuiSDL uses disables corner-rounding. For rectangles, the fixed-point rasterizer doesn't need to run.
2) The fixed-point triangle rasterizer in ImGuiSDL obviously doesn't match the quality of DirectX, and suffers from some artifacts that I haven't bothered to track down. There's no AA for an example. There are also details in triangle edge filling rules that the software rasterizer doesn't follow.

If your game is written with DirectX, just use the DirectX renderer that ImGui ships with. If with "I wrote a little game with SDL2 / DX" you mean something else, you could look into forcing SDL_Renderer to be created with a DirectX driver and try to dig the DirectX instance handle (if that even is a thing, I have no experience with DirectX) somehow out of SDL, and use the DirectX renderer with that.

Alternatively you could try to improve the fixed-point rasterizer, but I find it unlikely that you'd come up with a performant-enough solution for matching the default ImGui quality anyways, since in its core ImGuiSDL is a software renderer.

**Comment by DaveInDev** [comment]
Thank you very much for your answer. Yes about the "quality" that's what you said : no AA in general, more square shapes ,and every objects like white triangles or radio buttons or checkbox tick and even fonts seems to be "coarse" in the diagonals. For my game, I do not use DX directly but only SDL calls for everything (keyboard, mouse, textures, graphics, viewports, timing, etc...). SDL has indead a DX renderer that I am using. But I have effectively no idea on how to make SDL and ImGui share the same "DX handle" if that exists.... I will dive into that direction. Have a nice evening (or day, wherever you are ;-).
